services:
  app:
    image: swift:6.0
    volumes:
      - ..:/workspace
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: todos
      POSTGRES_USER: todos_app
      POSTGRES_PASSWORD: some_secret_password
    command: sleep infinity

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: todos_app
      POSTGRES_PASSWORD: some_secret_password
    ports:
      - 5432:5432

volumes:
  postgres-data:
